### ISSUE TITLE
The URL … does not seem to accept DAV requests

### ISSUE THREAD

**Issue by hugoroy** [dengste/org-caldav#30]
Hello, I have a calDAV server provided with Kolab 3.1 (using SabreDAV)

I tried to set up org-caldav but when I sync I get 

```
 The URL https://totosh.ampoliros.net/iRony/calendars/hugo@ampoliros.net/642e3b…/ does not seem to accept DAV requests
```

However this is strange. I can access these files with webDAV fine, I also configured some other things for the cardDAV part. I tried different settings (i tried both the "human" calendar id and the long-numerical-id) etc. but none of them worked.

I'm wondering if i'm missing some emacs package! I'm running emacs 24.3.1

Thanks for your help

**Comment by gour** [comment]
Hello,

Today I tried with Emacs-24.4.1, latest org-caldav from MELPA and using OC-7.x..First few attempts reported the same "The URL ... does not seem to accpet DAV requests and then after another attempt, it worked...

**Comment by MaksVal** [comment]
Hi! 
Is fixed the problem?

**Comment by hugoroy** [comment]
No, I still have this issue. 

As said in several comments, I have to launch M-x org-caldav-sync twice in order to get a sync; which is a bit annoying.

**Comment by thaaophz** [comment]
> I have to launch M-x org-caldav-sync twice in order to get a sync; which is a bit annoying.

I had the same error but now I'm using the [.authinfo.gpg file](https://github.com/dengste/org-caldav#storing-authentication-information-in-authinfonetrc) and it works great.

**Comment by dengste** [comment]
The thing with having to run org-caldav-sync twice is Emacs bug 10478. I've implemented a workaround that will run authentication several times before giving up.
